# Generated by Django 3.0 on 2020-06-09 18:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ques', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('com', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgeGroup',
            fields=[
                ('AgeGroupID', models.AutoField(db_column='AgeGroupID', primary_key=True, serialize=False)),
                ('AgeGroupName', models.CharField(db_column='AgeGroupName', max_length=30)),
                ('created_on', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='AgeGroupClass',
            fields=[
                ('AgeGroupClassID', models.AutoField(db_column='AgeGroupClassID', primary_key=True, serialize=False)),
                ('AgeGroupID', models.ForeignKey(db_column='AgeGroupID', null=True, on_delete=django.db.models.deletion.CASCADE, to='cmp.AgeGroup')),
                ('ClassID', models.ForeignKey(db_column='classID', null=True, on_delete=django.db.models.deletion.CASCADE, to='com.Class')),
            ],
        ),
        migrations.CreateModel(
            name='competition',
            fields=[
                ('competitionID', models.AutoField(db_column='competitionID', primary_key=True, serialize=False)),
                ('competitionName', models.CharField(max_length=50)),
                ('competitionInfo', models.CharField(max_length=100)),
                ('startDate', models.DateTimeField()),
                ('endDate', models.DateTimeField()),
                ('testDuration', models.TimeField()),
                ('competitionType', models.ForeignKey(db_column='competitionType', default=111002, on_delete=django.db.models.deletion.CASCADE, to='com.code')),
            ],
        ),
        migrations.CreateModel(
            name='competitionAge',
            fields=[
                ('competitionAgeID', models.AutoField(db_column='competitionAgeID', primary_key=True, serialize=False)),
                ('defaultBonusMarks', models.IntegerField()),
                ('AgeGroupClassID', models.ForeignKey(db_column='AgeGroupClassID', null=True, on_delete=django.db.models.deletion.CASCADE, to='cmp.AgeGroupClass')),
                ('competitionID', models.ForeignKey(db_column='competitionID', null=True, on_delete=django.db.models.deletion.CASCADE, to='cmp.competition')),
            ],
        ),
        migrations.CreateModel(
            name='competitionQuestion',
            fields=[
                ('competitionQuestionID', models.AutoField(db_column='competitionQuestionID', primary_key=True, serialize=False)),
                ('competitionAgeID', models.ForeignKey(db_column='competitionAgeID', on_delete=django.db.models.deletion.CASCADE, to='cmp.competitionAge')),
                ('questionID', models.ForeignKey(db_column='questionID', on_delete=django.db.models.deletion.CASCADE, to='ques.question')),
                ('questionLevelCodeID', models.ForeignKey(db_column='questionLevelCodeID', default=107001, on_delete=django.db.models.deletion.CASCADE, related_name='questionLevelCodeID', to='com.code')),
            ],
        ),
        migrations.CreateModel(
            name='studentEnrollment',
            fields=[
                ('studentEnrollmentID', models.AutoField(db_column='studentEnrollmentID', primary_key=True, serialize=False)),
                ('timeTaken', models.TimeField()),
                ('score', models.IntegerField()),
                ('additionalTime', models.TimeField(null=True)),
                ('bonusMarks', models.IntegerField()),
                ('competitionAgeID', models.ForeignKey(db_column='competitionAgeID', on_delete=django.db.models.deletion.CASCADE, to='cmp.competitionAge')),
                ('languageCodeID', models.ForeignKey(db_column='languageCodeID', on_delete=django.db.models.deletion.CASCADE, to='com.code')),
                ('schoolClassID', models.ForeignKey(db_column='schoolClassID', default=1, on_delete=django.db.models.deletion.CASCADE, to='com.schoolClass')),
                ('userID', models.ForeignKey(db_column='userID', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='studentResponse',
            fields=[
                ('studentResponseID', models.AutoField(db_column='studentResponseID', primary_key=True, serialize=False)),
                ('ansText', models.CharField(max_length=20, null=True)),
                ('time', models.FloatField()),
                ('competitionQuestionID', models.ForeignKey(db_column='competitionQuestionID', on_delete=django.db.models.deletion.CASCADE, to='cmp.competitionQuestion')),
                ('optionTranslationID', models.ForeignKey(db_column='optionTranslationID', default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='ques.optionTranslation')),
                ('studentEnrollmentID', models.ForeignKey(db_column='studentEnrollmentID', on_delete=django.db.models.deletion.CASCADE, to='cmp.studentEnrollment')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionAge',
            fields=[
                ('QuestionAgeID', models.AutoField(db_column='QuestionAgeID', primary_key=True, serialize=False)),
                ('AgeGroupID', models.ForeignKey(db_column='AgeGroupID', null=True, on_delete=django.db.models.deletion.CASCADE, to='cmp.AgeGroup')),
                ('questionID', models.ForeignKey(db_column='questionID', on_delete=django.db.models.deletion.CASCADE, to='ques.question')),
                ('questionLevelCodeID', models.ForeignKey(db_column='questionLevelCodeID', on_delete=django.db.models.deletion.CASCADE, related_name='questionLevelCode', to='com.code')),
            ],
        ),
        migrations.CreateModel(
            name='competition_MarkScheme',
            fields=[
                ('competition_MarkSchemeID', models.AutoField(db_column='competition_MarkSchemeID', primary_key=True, serialize=False)),
                ('correctMarks', models.IntegerField()),
                ('incorrectMarks', models.IntegerField()),
                ('competitionAgeID', models.ForeignKey(db_column='competitionAgeID', on_delete=django.db.models.deletion.CASCADE, to='cmp.competitionAge')),
                ('questionLevelCodeID', models.ForeignKey(db_column='questionLevelCodeID', on_delete=django.db.models.deletion.CASCADE, to='com.code')),
            ],
        ),
    ]
