# Generated by Django 3.0 on 2020-06-09 18:18

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import usr.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('com', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('userID', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('loginID', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=500)),
                ('birthdate', models.DateField(null=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None)),
                ('email', models.CharField(max_length=70, null=True)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('created_by', models.CharField(default='default value', max_length=50)),
                ('modified_on', models.DateField(default=datetime.date(1997, 11, 11))),
                ('modified_by', models.CharField(default='default value', max_length=50)),
                ('gender', models.ForeignKey(db_column='gender', on_delete=django.db.models.deletion.CASCADE, related_name='Gender', to='com.code')),
                ('is_active', models.ForeignKey(db_column='is_active', default=106001, on_delete=django.db.models.deletion.CASCADE, related_name='is_active', to='com.code')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', usr.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('RoleID', models.IntegerField(primary_key=True, serialize=False)),
                ('RoleName', models.CharField(max_length=20)),
                ('RoleDescription', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('userRoleID', models.AutoField(primary_key=True, serialize=False)),
                ('RoleID', models.ForeignKey(db_column='roleID', on_delete=django.db.models.deletion.CASCADE, to='usr.Role')),
                ('userID', models.ForeignKey(db_column='userID', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserRoleLocation',
            fields=[
                ('userRoleLocationID', models.AutoField(db_column='userRoleLocationID', primary_key=True, serialize=False)),
                ('locationObjectID', models.IntegerField()),
                ('locationTypeCodeID', models.ForeignKey(db_column='locationTypeCodeID', default=109001, on_delete=django.db.models.deletion.CASCADE, to='com.code')),
                ('userRoleID', models.ForeignKey(db_column='userRoleID', on_delete=django.db.models.deletion.CASCADE, to='usr.UserRole')),
            ],
        ),
    ]
