# Generated by Django 2.2.7 on 2020-06-22 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='modified_on',
            field=models.DateField(auto_now_add=True),
        ),
    ]
